### ISSUE TITLE
Loading matrix

### ISSUE THREAD

**Issue by xih** [berkeley-dsc/destress#32]
@coryschillaci  @anasrferreira  @davclark  

When I try to load a txt file into BidMat I'm getting a column vector instead of a matrix. 

My input file is vectors.txt located in /var/local/destress and I tried load[F,D,I,L]MAT, however I am still getting 
scala> size(t)
res5: (Int, Int) = (3000001,1) which is a column vector. 

Any help on getting a correct n x m matrix. Or is my input file, vectors.txt, wrong ? 

Cheers

**Comment by DanielTakeshi** [comment]
It's almost certainly because the first line is a single number. I'm not sure why that's there. Try deleting it and load again. I load text files all the time, and I tried adding in a single number as the first line to see if that would screw it up, and loadFMat() only took the first number in each line to create a column vector.
